# Generated by Django 5.1.3 on 2024-12-06 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_bcondent_board_bcontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
